# Site settings
title: AeroCogito H7-Digital
description: High-performance STM32H743 flight controller for ArduPilot and Betaflight
baseurl: "/h7-digital-docs"  # repo name
url: "https://aerocogito.github.io"
permalink: pretty

# Theme
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Logo
logo: "/assets/images/AERO_COGITO_HYBRID-B.svg"
favicon_ico: "/assets/images/favicon.ico"
social_image: "/assets/images/og-1200x630.png"

# Color scheme (options: nil, dark, or custom)
color_scheme: dark

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Navigation
aux_links:
  "Buy H7-Digital":
    - "https://aerocogito.com/store/p/h7-digital"
  "Secure Firmware":
    - "https://github.com/AeroCogito/h7-digital-firmware"
  "GitHub":
    - "https://github.com/AeroCogito/h7-digital-docs"
aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2025 AeroCogito. NDAA-compliant hardware designed and manufactured in the USA."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/AeroCogito/h7-digital"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"

# Callouts (custom content blocks)
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Kramdown settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - "*.sh"
  - "*.py"
